#!/bin/sh

/bin/mknod /dev/null c 1 3
/bin/mknod /dev/port c 1 4
/bin/mknod /dev/zero c 1 5
/bin/mknod /dev/one c 1 6
/bin/mknod /dev/full c 1 7
/bin/mknod /dev/random c 1 8
/bin/mknod /dev/urandom c 1 9
/bin/mknod /dev/kmsg c 1 11

/bin/mkdir /proc/
/bin/mount proc /proc -t proc
/bin/mkdir /sys/
/bin/mount sys /sys -t sysfs
/bin/mount -t debugfs none /sys/kernel/debug/

/bin/sh
